export const REQUEST_SOLUTIONS = 'REQUEST_SOLUTIONS';
export const FAILED_TO_GET_SOLUTIONS = 'FAILED_TO_GET_SOLUTIONS';
export const GOT_SOLUTIONS = 'GOT_SOLUTIONS';

export const SET_MATRIX = 'SET_MATRIX';

// export const GENERATE_RANDOM_MATRIX = 'GENERATE_RANDOM_MATRIX';
// export const INSERT_MATRIX_COLUMN = 'INSERT_MATRIX_COLUMN';
// export const REMOVE_MATRIX_COLUMN = 'REMOVE_MATRIX_COLUMN';
// export const INSERT_MATRIX_ROW = 'INSERT_MATRIX_ROW';
// export const REMOVE_MATRIX_ROW = 'REMOVE_MATRIX_ROW';
// export const SET_MATRIX_CELL_VALUE = 'SET_MATRIX_CELL_VALUE';
// export const SET_RANDOM_MATRIX_MIN_COLUMN_COUNT = 'SET_RANDOM_MATRIX_MIN_COLUMN_COUNT';
// export const SET_RANDOM_MATRIX_MAX_COLUMN_COUNT = 'SET_RANDOM_MATRIX_MAX_COLUMN_COUNT';
// export const SET_RANDOM_MATRIX_MIN_ROW_COUNT = 'SET_RANDOM_MATRIX_MIN_ROW_COUNT';
// export const SET_RANDOM_MATRIX_MAX_ROW_COUNT = 'SET_RANDOM_MATRIX_MAX_ROW_COUNT';
// export const SET_RANDOM_MATRIX_MIN_CELL_VALUE = 'SET_RANDOM_MATRIX_MIN_CELL_VALUE';
// export const SET_RANDOM_MATRIX_MAX_CELL_VALUE = 'SET_RANDOM_MATRIX_MAX_CELL_VALUE';
// export const TOGGLE_MATRIX_EDIT_MODE = 'TOGGLE_MATRIX_EDIT_MODE';
