export const REQUEST_SOLUTIONS = 'REQUEST_SOLUTIONS';
export const FAILED_TO_GET_SOLUTIONS = 'FAILED_TO_GET_SOLUTIONS';
export const GOT_SOLUTIONS = 'GOT_SOLUTIONS';
export const RESET_SOLUTIONS = 'RESET_SOLUTIONS';
export const SET_PREVIEW_SOLUTION = 'SET_PREVIEW_SOLUTION';
export const SET_ACTIVE_SOLUTION = 'SET_ACTIVE_SOLUTION';
export const SET_NEXT_ACTIVE_SOLUTION = 'SET_NEXT_ACTIVE_SOLUTION';
export const SET_PREVIOUS_ACTIVE_SOLUTION = 'SET_PREVIOUS_ACTIVE_SOLUTION';

export const SET_MATRIX = 'SET_MATRIX';
export const SET_MATRIX_CELL = 'SET_MATRIX_CELL';
export const REQUEST_RANDOM_MATRIX = 'REQUEST_RANDOM_MATRIX';
export const REQUEST_MATRIX_CHANGE = 'REQUEST_MATRIX_CHANGE';

export const TOGGLE_CREATE_MATRIX_UI = 'TOGGLE_CREATE_MARIX_UI';
export const TOGGLE_INTRODUCTION_UI = 'TOGGLE_INTRODUCTION_UI';
export const SET_CREATE_MATRIX_ROW_COUNT = 'SET_CREATE_MATRIX_ROW_COUNT';
export const SET_CREATE_MATRIX_COLUMN_COUNT = 'SET_CREATE_MATRIX_COLUMN_COUNT';
