export const REQUEST_MATRIX_SOLUTION = 'REQUEST_MATRIX_SOLUTION';
export const FAILED_TO_GET_MATRIX_SOLUTION = 'FAILED_TO_GET_MATRIX_SOLUTION';
export const GOT_MATRIX_SOLUTION = 'GOT_MATRIX_SOLUTION';

export const GENERATE_RANDOM_MATRIX = 'GENERATE_RANDOM_MATRIX';
export const INSERT_MATRIX_COLUMN = 'INSERT_MATRIX_COLUMN';
export const REMOVE_MATRIX_COLUMN = 'REMOVE_MATRIX_COLUMN';
export const INSERT_MATRIX_ROW = 'INSERT_MATRIX_ROW';
export const REMOVE_MATRIX_ROW = 'REMOVE_MATRIX_ROW';
export const SET_MATRIX_CELL_VALUE = 'SET_MATRIX_CELL_VALUE';
export const SET_RANDOM_MATRIX_MIN_COLUMN_COUNT = 'SET_RANDOM_MATRIX_MIN_COLUMN_COUNT';
export const SET_RANDOM_MATRIX_MAX_COLUMN_COUNT = 'SET_RANDOM_MATRIX_MAX_COLUMN_COUNT';
export const SET_RANDOM_MATRIX_MIN_ROW_COUNT = 'SET_RANDOM_MATRIX_MIN_ROW_COUNT';
export const SET_RANDOM_MATRIX_MAX_ROW_COUNT = 'SET_RANDOM_MATRIX_MAX_ROW_COUNT';
export const SET_RANDOM_MATRIX_MIN_CELL_VALUE = 'SET_RANDOM_MATRIX_MIN_CELL_VALUE';
export const SET_RANDOM_MATRIX_MAX_CELL_VALUE = 'SET_RANDOM_MATRIX_MAX_CELL_VALUE';
export const TOGGLE_MATRIX_EDIT_MODE = 'TOGGLE_MATRIX_EDIT_MODE';
